version: '2'
services:
  app:
    build: .
    command: iex -S mix phoenix.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "53:53"
    links:
      - db
      - redis
  db:
    image: postgres:9.5
    ports:
      - "54320:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_dev
  redis:
    image: redis:latest

volumes:
  data:
    external:
      name: phoenix_vol
